# action.yml
name: 'Simple Node.js Action'
description: 'A simple action to run a Node.js script that performs an operation'
inputs:
  log-message:
    description: 'The message to log'
    required: true
    default: 'Hello, world!'

runs:
  using: 'node20'
  main: 'index.js'
