# action.yml
name: 'Simple Node.js Action'
description: 'A simple action to run a Node.js script that performs an operation'
inputs:
  log-message:
    description: 'The message to log'
    required: true
    default: 'Hello, world!'

runs:
  using: "composite"
  steps:
    - name: Set up Node.js 
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ${{ github.action_path }}/package-lock.json
        
    - name: install dependency
      run: npm install @actions/core
      shell: bash
      
    - name: run node script
      run: node ${{ github.action_path }}/index.js
      shell: bash
