# action.yml
name: 'Simple Node.js Action'
description: 'A simple action to run a Node.js script that performs an operation'
inputs:
  log-message:
    description: 'The message to log'
    required: true
    default: 'Hello, world!'

runs:
  using: 'node12'
  main: 'dist/index.js'  # Ensure this path is correct; could be index.js or another script

  steps:
    - name: 'Setup Node.js environment'
      run: |
        # Setup Node.js
        curl -sL https://deb.nodesource.com/setup_14.x | bash -
        apt-get install -y nodejs
        node -v
        npm -v

    - name: 'Install dependencies'
      run: |
        npm install

    - name: 'Run script'
      run: |
        node index.js
