# .github/workflows/reusable.yml
name: 'Reusable Node.js Action Workflow'
on:
  workflow_dispatch:
    inputs:
      log-message:
        required: true
        type: string
  
  workflow_call:
    inputs:
      log-message:
        required: true
        type: string

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4


      - name: 'Set up Node.js'
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.18.0'  # Specify your desired Node.js version

      - name: 'Install dependencies'
        run: npm install @actions/core
        # working-directory: ./  # Adjust this if your package.json is in a different directory

      # - name: 'List directory contents' 
      #   run: |
      #     cat package-lock.json
      #     pwd
      #     ls -lah
      #     ls -R
        
      - name: 'Run Node.js Action'
        uses: priteshks/test-action@main # This points to the current repository containing the action.yml file
        with:
          log-message: ${{ inputs.log-message }}
