name: Conditional Steps

on: #[push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: First Step
        id: step1
        if: github.repository == 'priteshks/not-repo'
        run: echo "Running the first step"

      - name: Second Step
        if: github.repository == 'priteshks/not-repo'
        id: step2
        run: echo "Running the second step"  # Simulating failure for demonstration

      - name: Conditional Step
        if: ${{ steps.step1.outcome == 'failure' || steps.step1.outcome == 'skipped' }}
        run: echo "This step runs if the first step failed or was skipped"
